name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: repository
          user: gregor7008
          repo: butler-george
          plugin_lines: yes
          plugin_followup: yes
          plugin_projects: yes
          plugin_projects_repositories: gregor7008/butler-george/projects/2
          plugin_licenses: yes
          plugin_licenses_setup: npm ci
          plugin_licenses_legal: no
          plugin_licenses_ratio: yes