name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  repository-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: repository
          repo: Butler-George
          plugin_lines: yes
          plugin_followup: yes
          plugin_projects: yes
          plugin_projects_repositories: Gregor7008/Butler-George/projects/2
#         plugin_licenses: yes
#         plugin_licenses_setup: npm ci
#         plugin_licenses_legal: no
#         plugin_licenses_ratio: yes